version: '3'

services:

  ariadne-client:
    build:
      context: client
      dockerfile: docker/client-production.dockerfile
    restart: always
    container_name: unpathd
    environment:
      VIRTUAL_HOST: ads24unpathd0,unpathd.ads.ac.uk
      VIRTUAL_PATH: /


  ariadne-server:
    build:
      context: .
      dockerfile: server/docker/server.dockerfile
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./server/:/var/www/
    container_name: unpathd-api
    environment:
      VIRTUAL_HOST: ads24unpathd0,unpathd.ads.ac.uk
      VIRTUAL_PATH: /api/

networks:
  default:
    external:
      name: nginx-proxy
