version: '3'

services:

  ariadne-client:
    build:
      context: client
      dockerfile: docker/client-demo.dockerfile
    container_name: unpathd
    environment:
      VIRTUAL_HOST: ads20demo0
      VIRTUAL_PATH: /unpathd/


  ariadne-server:
    build:
      context: .
      dockerfile: server/docker/server.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./server/:/var/www/
    container_name: unpathd-api
    environment:
      VIRTUAL_HOST: ads20demo0
      VIRTUAL_PATH: /unpathd-api/
      VIRTUAL_DEST: /

networks:
  default:
    external:
      name: nginx-proxy
